#!/bin/bash

. ./erl_node

case "$1" in
    status)
        $NODETOOL rpc axb_console status
        ;;
    stats)
        $NODETOOL rpc axb_console stats
        ;;
    online)
        $NODETOOL rpc axb_console set_online true $@
        ;;
    offline)
        $NODETOOL rpc axb_console set_online false $@
        ;;
    *)
        echo "Usage: $SCRIPT { status | stats | online <what> | offline <what> }"
        echo "  where <what> is one of the following:"
        echo "    <node> <adapter> [all | <domain>] [<direction>]"
        echo "    <node> <flowMgr> [all | <domain> | <flow>]"
        echo ""
esac

